services:
  leapfrog-job-search:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: leapfrog-job-search
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"